<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>MyAddin</AssemblyName>
    <RootNamespace>MyAddin</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>


  <!-- 
  <ItemGroup>
    <Reference Include="Put.DLL.Name.Here">
      <HintPath>lib\Put.DLL.Name.Here.dll</HintPath>
      <EmbedInteropTypes>false</EmbedInteropTypes>
    </Reference>
  </ItemGroup>
  -->
</Project>